# Generated by Django 4.2.2 on 2023-06-21 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('new_email', models.EmailField(max_length=100)),
                ('expiration_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
